DROP TABLE IF EXISTS STUDENTS;
CREATE TABLE STUDENTS(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255),
    MY_GROUP VARCHAR(15),
    COURSE VARCHAR(255),
    PHONE VARCHAR(11)
                     );
